/**
 * Todas las ligas listadas en https://www.soccerstats.com/leagues.asp al momento
 * de construir este proyecto. Cada `slug` es el valor del parámetro ?league= que
 * usa SoccerStats en todas sus páginas (latest.asp, table.asp, formtable.asp, etc.)
 *
 * SoccerStats agrega ligas nuevas y a veces cambia slugs entre temporadas.
 * Para refrescar esta lista en el futuro: abre https://www.soccerstats.com/leagues.asp
 * y actualiza/agrega filas siguiendo el mismo formato { region, name, slug }.
 *
 * `region` aquí es simplemente el país/ámbito, usado solo para agrupar en la web.
 *
 * Puedes comentar (anteponiendo //) las ligas que no te interesen para reducir
 * la cantidad de peticiones diarias — con ~150 ligas activas el scraping diario
 * es pesado y lento; se recomienda empezar con un subconjunto y ampliar después
 * de confirmar que todo funciona.
 */

module.exports = [
  { region: 'Albania', name: 'Albania - Abissnet Superiore', slug: 'albania' },
  { region: 'Argentina', name: 'Argentina - Liga Profesional - Apertura', slug: 'argentina' },
  { region: 'Argentina', name: 'Argentina - Liga Profesional - Clausura', slug: 'argentina2' },
  { region: 'Argentina', name: 'Argentina - Primera Nacional', slug: 'argentina3' },
  { region: 'Armenia', name: 'Armenia - Premier League', slug: 'armenia' },
  { region: 'Australia', name: 'Australia - A-League', slug: 'australia' },
  { region: 'Australia', name: 'Australia - A-League Women', slug: 'australia2' },
  { region: 'Australia', name: 'Australia - NPL Victoria', slug: 'australia3' },
  { region: 'Australia', name: 'Australia - NPL Queensland', slug: 'australia4' },
  { region: 'Australia', name: 'Australia - NPL Western Australia', slug: 'australia5' },
  { region: 'Australia', name: 'Australia - NPL South Australia', slug: 'australia6' },
  { region: 'Australia', name: 'Australia - NPL Northern NSW', slug: 'australia7' },
  { region: 'Australia', name: 'Australia - NPL Tasmania', slug: 'australia8' },
  { region: 'Australia', name: 'Australia - NPL Capital Territory', slug: 'australia10' },
  { region: 'Australia', name: 'Australia - NPL New South Wales', slug: 'australia11' },
  { region: 'Austria', name: 'Austria - Bundesliga', slug: 'austria' },
  { region: 'Austria', name: 'Austria - 2. Liga', slug: 'austria2' },
  { region: 'Azerbaijan', name: 'Azerbaijan - Premier League', slug: 'azerbaijan' },
  { region: 'Belarus', name: 'Belarus - Vysshaya Liga', slug: 'belarus' },
  { region: 'Belgium', name: 'Belgium - Pro League', slug: 'belgium' },
  { region: 'Belgium', name: 'Belgium - Challenger Pro League', slug: 'belgium2' },
  { region: 'Bosnia', name: 'Bosnia and Herzegovina - Premier Liga', slug: 'bosnia' },
  { region: 'Brazil', name: 'Brazil - Serie A', slug: 'brazil' },
  { region: 'Brazil', name: 'Brazil - Serie B', slug: 'brazil2' },
  { region: 'Brazil', name: 'Brazil - Serie C', slug: 'brazil3' },
  { region: 'Brazil', name: 'Brazil - Brasileiro Women', slug: 'brazil5' },
  { region: 'Bulgaria', name: 'Bulgaria - Parva Liga', slug: 'bulgaria' },
  { region: 'Bulgaria', name: 'Bulgaria - Vtora Liga', slug: 'bulgaria2' },
  { region: 'Canada', name: 'Canada - Premier League', slug: 'canada' },
  { region: 'Chile', name: 'Chile - Liga de Primera', slug: 'chile' },
  { region: 'Chile', name: 'Chile - Liga de Ascenso', slug: 'chile2' },
  { region: 'China', name: 'China - Super League', slug: 'china' },
  { region: 'China', name: 'China - League One', slug: 'china2' },
  { region: 'Colombia', name: 'Colombia - Primera A - Apertura', slug: 'colombia' },
  { region: 'Colombia', name: 'Colombia - Primera A - Clausura', slug: 'colombia2' },
  { region: 'Costa Rica', name: 'Costa Rica - Primera Div. - Apertura', slug: 'costarica' },
  { region: 'Costa Rica', name: 'Costa Rica - Primera Div. - Clausura', slug: 'costarica2' },
  { region: 'Croatia', name: 'Croatia - 1. HNL', slug: 'croatia' },
  { region: 'Cyprus', name: 'Cyprus - Cyprus League', slug: 'cyprus' },
  { region: 'Czech Republic', name: 'Czech Republic - 1. Liga', slug: 'czechrepublic' },
  { region: 'Czech Republic', name: 'Czech Republic - FNL', slug: 'czechrepublic2' },
  { region: 'Denmark', name: 'Denmark - Superligaen', slug: 'denmark' },
  { region: 'Denmark', name: 'Denmark - 1st Division', slug: 'denmark2' },
  { region: 'Denmark', name: 'Denmark - 2nd Division', slug: 'denmark3' },
  { region: 'Ecuador', name: 'Ecuador - Liga Pro', slug: 'ecuador' },
  { region: 'Egypt', name: 'Egypt - Premier League', slug: 'egypt' },
  { region: 'England', name: 'England - Premier League', slug: 'england' },
  { region: 'England', name: 'England - Championship', slug: 'england2' },
  { region: 'England', name: 'England - League One', slug: 'england3' },
  { region: 'England', name: 'England - League Two', slug: 'england4' },
  { region: 'England', name: 'England - National League', slug: 'england5' },
  { region: 'England', name: 'England - National L. North', slug: 'england6' },
  { region: 'England', name: 'England - National L. South', slug: 'england7' },
  { region: 'England', name: 'England - Isthmian league', slug: 'england8' },
  { region: 'England', name: 'England - Northern league', slug: 'england9' },
  { region: 'England', name: 'England - Southern Central', slug: 'england10' },
  { region: 'England', name: 'England - Southern South', slug: 'england11' },
  { region: 'England', name: 'England - Premier League 2', slug: 'england15' },
  { region: 'England', name: 'England - Women Super League', slug: 'england17' },
  { region: 'Estonia', name: 'Estonia - Meistriliiga', slug: 'estonia' },
  { region: 'Estonia', name: 'Estonia - Esiliiga', slug: 'estonia2' },
  { region: 'FaroeIslands', name: 'FaroeIslands - Premier League', slug: 'faroeislands' },
  { region: 'Finland', name: 'Finland - Veikkausliiga', slug: 'finland' },
  { region: 'Finland', name: 'Finland - Ykkosliga', slug: 'finland2' },
  { region: 'Finland', name: 'Finland - Ykkonen', slug: 'finland3' },
  { region: 'France', name: 'France - Ligue 1', slug: 'france' },
  { region: 'France', name: 'France - Ligue 2', slug: 'france2' },
  { region: 'France', name: 'France - National', slug: 'france3' },
  { region: 'France', name: 'France - Premiere Ligue Women', slug: 'france14' },
  { region: 'Georgia', name: 'Georgia - Erovnuli Liga', slug: 'georgia' },
  { region: 'Germany', name: 'Germany - Bundesliga', slug: 'germany' },
  { region: 'Germany', name: 'Germany - 2. Bundesliga', slug: 'germany2' },
  { region: 'Germany', name: 'Germany - 3. Liga', slug: 'germany3' },
  { region: 'Germany', name: 'Germany - Regionalliga Nord', slug: 'germany4' },
  { region: 'Germany', name: 'Germany - Regionalliga Nordost', slug: 'germany5' },
  { region: 'Germany', name: 'Germany - Regionalliga West', slug: 'germany6' },
  { region: 'Germany', name: 'Germany - Regionalliga Sudwest', slug: 'germany7' },
  { region: 'Germany', name: 'Germany - Regionalliga Bayern', slug: 'germany8' },
  { region: 'Germany', name: 'Germany - Bundesliga Women', slug: 'germany23' },
  { region: 'Greece', name: 'Greece - Super League', slug: 'greece' },
  { region: 'Guatemala', name: 'Guatemala - Liga Nacional - Apertura', slug: 'guatemala' },
  { region: 'Guatemala', name: 'Guatemala - Liga Nacional - Clausura', slug: 'guatemala2' },
  { region: 'Hungary', name: 'Hungary - NB I', slug: 'hungary' },
  { region: 'Hungary', name: 'Hungary - NB II', slug: 'hungary2' },
  { region: 'Iceland', name: 'Iceland - Besta deild', slug: 'iceland' },
  { region: 'Iceland', name: 'Iceland - 1. Deild', slug: 'iceland2' },
  { region: 'Iceland', name: 'Iceland - 2. Deild', slug: 'iceland3' },
  { region: 'Indonesia', name: 'Indonesia - Liga 1', slug: 'indonesia' },
  { region: 'Iran', name: 'Iran - Pro League', slug: 'iran' },
  { region: 'Ireland', name: 'Ireland - Premier Division', slug: 'ireland' },
  { region: 'Ireland', name: 'Ireland - First Division', slug: 'ireland2' },
  { region: 'Ireland', name: 'Ireland - Women National League', slug: 'ireland3' },
  { region: 'Israel', name: 'Israel - Ligat HaAl', slug: 'israel' },
  { region: 'Italy', name: 'Italy - Serie A', slug: 'italy' },
  { region: 'Italy', name: 'Italy - Serie B', slug: 'italy2' },
  { region: 'Italy', name: 'Italy - Serie C - Group A', slug: 'italy3' },
  { region: 'Italy', name: 'Italy - Serie C - Group B', slug: 'italy4' },
  { region: 'Italy', name: 'Italy - Serie C - Group C', slug: 'italy5' },
  { region: 'Italy', name: 'Italy - Serie A Women', slug: 'italy17' },
  { region: 'Japan', name: 'Japan - J1 League', slug: 'japan' },
  { region: 'Japan', name: 'Japan - J2 League', slug: 'japan2' },
  { region: 'Japan', name: 'Japan - J3 League', slug: 'japan3' },
  { region: 'Kazakhstan', name: 'Kazakhstan - Premier League', slug: 'kazakhstan' },
  { region: 'Kuwait', name: 'Kuwait - Premier League', slug: 'kuwait' },
  { region: 'Latvia', name: 'Latvia - Virsliga', slug: 'latvia' },
  { region: 'Lithuania', name: 'Lithuania - A Lyga', slug: 'lithuania' },
  { region: 'Malaysia', name: 'Malaysia - Super League', slug: 'malaysia' },
  { region: 'Mexico', name: 'Mexico - Liga MX - Apertura', slug: 'mexico' },
  { region: 'Mexico', name: 'Mexico - Liga MX - Clausura', slug: 'mexico2' },
  { region: 'Mexico', name: 'Mexico - Liga Expansion - Apertura', slug: 'mexico3' },
  { region: 'Moldova', name: 'Moldova - Divizia Nationala', slug: 'moldova' },
  { region: 'Montenegro', name: 'Montenegro - First League', slug: 'montenegro' },
  { region: 'Morocco', name: 'Morocco - Botola Pro', slug: 'morocco' },
  { region: 'Netherlands', name: 'Netherlands - Eredivisie', slug: 'netherlands' },
  { region: 'Netherlands', name: 'Netherlands - Eerste Divisie', slug: 'netherlands2' },
  { region: 'Netherlands', name: 'Netherlands - Tweede Divisie', slug: 'netherlands3' },
  { region: 'Northern Ireland', name: 'Northern Ireland - NIFL Premiership', slug: 'northernireland' },
  { region: 'North Macedonia', name: 'North Macedonia - First League', slug: 'northmacedonia' },
  { region: 'Norway', name: 'Norway - Eliteserien', slug: 'norway' },
  { region: 'Norway', name: 'Norway - 1st Division', slug: 'norway2' },
  { region: 'Norway', name: 'Norway - Division 2 - Gr. 1', slug: 'norway3' },
  { region: 'Norway', name: 'Norway - Division 2 - Gr. 2', slug: 'norway4' },
  { region: 'Norway', name: 'Norway - Toppserien Women', slug: 'norway11' },
  { region: 'Paraguay', name: 'Paraguay - Primera Div. - Apertura', slug: 'paraguay' },
  { region: 'Paraguay', name: 'Paraguay - Primera Div. - Clausura', slug: 'paraguay2' },
  { region: 'Peru', name: 'Peru - Liga 1 - Apertura', slug: 'peru' },
  { region: 'Peru', name: 'Peru - Liga 1 - Clausura', slug: 'peru2' },
  { region: 'Poland', name: 'Poland - Ekstraklasa', slug: 'poland' },
  { region: 'Poland', name: 'Poland - 1. Liga', slug: 'poland2' },
  { region: 'Poland', name: 'Poland - 2. Liga', slug: 'poland3' },
  { region: 'Portugal', name: 'Portugal - Liga Portugal', slug: 'portugal' },
  { region: 'Portugal', name: 'Portugal - Liga Portugal 2', slug: 'portugal2' },
  { region: 'Qatar', name: 'Qatar - Stars League', slug: 'qatar' },
  { region: 'Romania', name: 'Romania - Liga 1', slug: 'romania' },
  { region: 'Russia', name: 'Russia - Premier League', slug: 'russia' },
  { region: 'Saudi Arabia', name: 'Saudi Arabia - Professional League', slug: 'saudiarabia' },
  { region: 'Scotland', name: 'Scotland - Premiership', slug: 'scotland' },
  { region: 'Scotland', name: 'Scotland - Championship', slug: 'scotland2' },
  { region: 'Scotland', name: 'Scotland - League One', slug: 'scotland3' },
  { region: 'Scotland', name: 'Scotland - League Two', slug: 'scotland4' },
  { region: 'Serbia', name: 'Serbia - Super Liga', slug: 'serbia' },
  { region: 'Singapore', name: 'Singapore - Premier League', slug: 'singapore' },
  { region: 'Slovakia', name: 'Slovakia - 1. Liga', slug: 'slovakia' },
  { region: 'Slovenia', name: 'Slovenia - Prva Liga', slug: 'slovenia' },
  { region: 'South Africa', name: 'South Africa - Premier Division', slug: 'southafrica' },
  { region: 'South Korea', name: 'South Korea - K League 1', slug: 'southkorea' },
  { region: 'South Korea', name: 'South Korea - K League 2', slug: 'southkorea2' },
  { region: 'South Korea', name: 'South Korea - WK League Women', slug: 'southkorea4' },
  { region: 'Spain', name: 'Spain - LaLiga', slug: 'spain' },
  { region: 'Spain', name: 'Spain - LaLiga2', slug: 'spain2' },
  { region: 'Spain', name: 'Spain - Primera RFEF - Gr. 1', slug: 'spain3' },
  { region: 'Spain', name: 'Spain - Primera RFEF - Gr. 2', slug: 'spain4' },
  { region: 'Sweden', name: 'Sweden - Allsvenskan', slug: 'sweden' },
  { region: 'Sweden', name: 'Sweden - Superettan', slug: 'sweden2' },
  { region: 'Sweden', name: 'Sweden - Div 1 - Norra', slug: 'sweden3' },
  { region: 'Sweden', name: 'Sweden - Div 1 - Sodra', slug: 'sweden4' },
  { region: 'Sweden', name: 'Sweden - Allsvenskan Women', slug: 'sweden11' },
  { region: 'Switzerland', name: 'Switzerland - Super League', slug: 'switzerland' },
  { region: 'Switzerland', name: 'Switzerland - Challenge League', slug: 'switzerland2' },
  { region: 'Thailand', name: 'Thailand - Thai League 1', slug: 'thailand' },
  { region: 'Turkiye', name: 'Turkiye - Super Lig', slug: 'turkey' },
  { region: 'Turkiye', name: 'Turkiye - 1. Lig', slug: 'turkey2' },
  { region: 'UAE', name: 'UAE - Pro League', slug: 'uae' },
  { region: 'Ukraine', name: 'Ukraine - Premier League', slug: 'ukraine' },
  { region: 'Uruguay', name: 'Uruguay - Liga AUF Uruguaya - Apertura', slug: 'uruguay' },
  { region: 'Uruguay', name: 'Uruguay - Liga AUF Uruguaya - Intermediate', slug: 'uruguay2' },
  { region: 'Uruguay', name: 'Uruguay - Liga AUF Uruguaya - Clausura', slug: 'uruguay3' },
  { region: 'USA', name: 'USA - MLS', slug: 'usa' },
  { region: 'USA', name: 'USA - USL Championship', slug: 'usa2' },
  { region: 'USA', name: 'USA - USL League One', slug: 'usa3' },
  { region: 'USA', name: 'USA - NWSL', slug: 'usa6' },
  { region: 'USA', name: 'USA - USL Super League', slug: 'usa7' },
  { region: 'Venezuela', name: 'Venezuela - Liga FUTVE - Apertura', slug: 'venezuela' },
  { region: 'Venezuela', name: 'Venezuela - Liga FUTVE - Clausura', slug: 'venezuela2' },
  { region: 'Wales', name: 'Wales - Cymru Premier', slug: 'wales' },

  // Competiciones internacionales de clubes (formato distinto: mezclan equipos de
  // ligas diferentes, por eso son menos fiables para el patrón PPG/racha, pero
  // las dejamos disponibles por si las quieres incluir).
  { region: 'Internacional', name: 'Champions League', slug: 'cleague' },
  { region: 'Internacional', name: 'Europa League', slug: 'uefa' },
  { region: 'Internacional', name: 'Conference League', slug: 'uefaconference' },
  { region: 'Internacional', name: 'Copa Libertadores', slug: 'copalibertadores' },
  { region: 'Internacional', name: 'Copa Sudamericana', slug: 'copasudamericana' },
];
